=== JannikArndt/Musicista/Collection/CollectionItem.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CategoryWork" nillable="true" type="CategoryWork" />
  <xs:complexType name="CategoryWork">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Meta" type="MetaData" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Filepath" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="MetaData">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Subtitle" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="People" type="People" />
      <xs:element minOccurs="0" maxOccurs="1" name="Collection" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Opus" type="OpusNumber" />
      <xs:element minOccurs="1" maxOccurs="1" name="Epoch" type="Epoch" />
      <xs:element minOccurs="1" maxOccurs="1" name="Form" type="Form" />
      <xs:element minOccurs="0" maxOccurs="1" name="Dates" type="Dates" />
      <xs:element minOccurs="0" maxOccurs="1" name="Dedication" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="AverageDuration" type="xs:double" />
      <xs:element minOccurs="1" maxOccurs="1" name="BeatsPerMinute" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="Key" type="MusicalKey" />
      <xs:element minOccurs="0" maxOccurs="1" name="Album" type="Album" />
      <xs:element minOccurs="0" maxOccurs="1" name="Copyright" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Reduction" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Weblink" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Notes" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Software" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="People">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Composers" type="ArrayOfComposer" />
      <xs:element minOccurs="0" maxOccurs="1" name="Lyricists" type="ArrayOfPerson" />
      <xs:element minOccurs="0" maxOccurs="1" name="Arrangers" type="ArrayOfPerson" />
      <xs:element minOccurs="0" maxOccurs="1" name="Producers" type="ArrayOfPerson" />
      <xs:element minOccurs="0" maxOccurs="1" name="Interpreters" type="ArrayOfPerson" />
      <xs:element minOccurs="0" maxOccurs="1" name="OtherPersons" type="ArrayOfPerson" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfComposer">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Composer" nillable="true" type="Composer" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Composer">
    <xs:complexContent mixed="false">
      <xs:extension base="Person" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Person">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="FirstName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="MiddleName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="LastName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Role" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Misc" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Born" type="xs:dateTime" />
      <xs:element minOccurs="0" maxOccurs="1" name="Died" type="xs:dateTime" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfPerson">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Person" nillable="true" type="Person" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OpusNumber">
    <xs:attribute name="Posthum" type="xs:boolean" />
    <xs:attribute name="Number" type="xs:int" use="required" />
    <xs:attribute name="SubNumber" type="xs:int" use="required" />
  </xs:complexType>
  <xs:simpleType name="Epoch">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Medieval" />
      <xs:enumeration value="Renaissance" />
      <xs:enumeration value="Baroque" />
      <xs:enumeration value="Classical" />
      <xs:enumeration value="Romantic" />
      <xs:enumeration value="Modern" />
      <xs:enumeration value="TwentiethCentury" />
      <xs:enumeration value="Contemporary" />
      <xs:enumeration value="TwentyFirstCentury" />
      <xs:enumeration value="Pop" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Form">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Symphony" />
      <xs:enumeration value="Concerto" />
      <xs:enumeration value="Sonata" />
      <xs:enumeration value="Ouverture" />
      <xs:enumeration value="Opera" />
      <xs:enumeration value="Lied" />
      <xs:enumeration value="Other" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Dates">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Composition" type="DateEvent" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Performances" type="Performance" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Publications" type="Publication" />
      <xs:element minOccurs="0" maxOccurs="1" name="Engraving" type="Engraving" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Other" type="DateEvent" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DateEvent">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Date" type="xs:dateTime" use="required" />
        <xs:attribute name="Place" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Engraving">
    <xs:simpleContent>
      <xs:extension base="DateEvent">
        <xs:attribute name="Typesetter" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Publication">
    <xs:simpleContent>
      <xs:extension base="DateEvent">
        <xs:attribute name="IsFirst" type="xs:boolean" use="required" />
        <xs:attribute name="Publisher" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Performance">
    <xs:simpleContent>
      <xs:extension base="DateEvent">
        <xs:attribute name="IsFirst" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="MusicalKey">
    <xs:attribute name="Step" type="Step" use="required" />
    <xs:attribute name="Gender" type="Gender" use="required" />
  </xs:complexType>
  <xs:simpleType name="Step">
    <xs:restriction base="xs:string">
      <xs:enumeration value="C" />
      <xs:enumeration value="CSharp" />
      <xs:enumeration value="DFlat" />
      <xs:enumeration value="D" />
      <xs:enumeration value="DSharp" />
      <xs:enumeration value="EFlat" />
      <xs:enumeration value="E" />
      <xs:enumeration value="ESharp" />
      <xs:enumeration value="FFlat" />
      <xs:enumeration value="F" />
      <xs:enumeration value="FSharp" />
      <xs:enumeration value="GFlat" />
      <xs:enumeration value="G" />
      <xs:enumeration value="GSharp" />
      <xs:enumeration value="AFlat" />
      <xs:enumeration value="A" />
      <xs:enumeration value="ASharp" />
      <xs:enumeration value="BFlat" />
      <xs:enumeration value="B" />
      <xs:enumeration value="BSharp" />
      <xs:enumeration value="CFlat" />
      <xs:enumeration value="Unknown" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Gender">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Major" />
      <xs:enumeration value="Minor" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Album">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Label" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Published" type="xs:dateTime" />
      <xs:element minOccurs="1" maxOccurs="1" name="Duration" type="TimeSpan" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TimeSpan" />
  <xs:element name="Collection" nillable="true" type="CollectionBase" />
  <xs:complexType name="CollectionBase">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Composer" type="CollectionComposer" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CollectionComposer">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Category" type="CollectionCategory" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Born" type="xs:int" use="required" />
    <xs:attribute name="Died" type="xs:int" use="required" />
    <xs:attribute name="Image" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="CollectionCategory">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Work" type="CategoryWork" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="CollectionCategory" nillable="true" type="CollectionCategory" />
  <xs:element name="CollectionComposer" nillable="true" type="CollectionComposer" />
</xs:schema>

=== JannikArndt/Musicista/setup/Collection.xml
<?xml version="1.0" encoding="utf-8"?>
<Collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="CollectionItem.xsd">
	<Composer Name="Arndt" Born="1989" Image="http://www.jannikarndt.de/wp-content/uploads/2014/05/cropped-2014-05-04-mit-Stock.jpg">
		<Category Name="Examples">
			<Work Name="Abendstück Nr. 17" Filepath="http://www.musicistaapp.de/download/scores/Arndt-Abendstueck17.musicista">
				<Meta>
					<Title>Abendstück No. 17</Title>
					<People>
						<Composer FirstName="Jannik" LastName="Arndt"/>
					</People>
					<Collection/>
					<Opus Number="0" SubNumber="0"/>
					<Epoch>None</Epoch>
					<Form>Other</Form>
					<Dates>
						<Engraving Date="2014-06-10" Typesetter="Jannik Arndt"/>
					</Dates>
					<AverageDuration>0</AverageDuration>
					<BeatsPerMinute>0</BeatsPerMinute>
					<Copyright>Copyright © Jannik Arndt</Copyright>
					<Software>Musicista 1.0</Software>
				</Meta>
			</Work>
			<Work Name="Benchmark" Filepath="http://www.musicistaapp.de/download/scores/Benchmark.musicista">
				<Meta>
					<Title>Benchmark Score</Title>
					<Subtitle>For testing scorewriters</Subtitle>
					<People>
						<Composer FirstName="Jannik" LastName="Arndt"/>
						<Lyricist FirstName="William" LastName="Shake-Beer"/>
					</People>
					<Collection/>
					<Opus Number="0" SubNumber="0"/>
					<Epoch>None</Epoch>
					<Form>Other</Form>
					<Dates>
						<Engraving Date="2014-08-11" Typesetter="Jannik Arndt"/>
					</Dates>
					<AverageDuration>0</AverageDuration>
					<BeatsPerMinute>0</BeatsPerMinute>
					<Copyright>Copyright © 2014</Copyright>
					<Software>Musicista 1.0</Software>
				</Meta>
			</Work>
			<Work Name="Doubling" Filepath="http://www.musicistaapp.de/download/scores/Doubling.musicista">
				<Meta>
					<Title>Example Piece with quite a very long title</Title>
					<People>
						<Composer FirstName="Jannik" LastName="Arndt"/>
					</People>
					<Collection/>
					<Opus Number="0" SubNumber="0"/>
					<Epoch>TwentyFirstCentury</Epoch>
					<Form>Lied</Form>
					<Dates>
						<Engraving Date="2014-09-27" Typesetter="Jannik Arndt"/>
					</Dates>
					<AverageDuration>0</AverageDuration>
					<BeatsPerMinute>0</BeatsPerMinute>
					<Copyright>Copyright © </Copyright>
					<Notes>Use this file to test the algorithms!</Notes>
					<Software>Musicista 1.0</Software>
				</Meta>
			</Work>
		</Category>
	</Composer>
	<Composer Name="Beethoven" Born="1770" Died="1827" Image="images/Beethoven.jpg">
		<Category Name="Sonatas">
			<Work Name="Sonate Nr. 1" Filepath="http://www.musicistaapp.de/download/scores/Beethoven-Sonate1.musicista">
				<Meta>
					<Title>Sonate No. 1</Title>
					<People>
						<Composer FirstName="Ludwig" MiddleName="van" LastName="Beethoven"/>
					</People>
					<Collection/>
					<Opus Number="2" SubNumber="1"/>
					<Epoch>Classical</Epoch>
					<Form>Sonata</Form>
					<Dates>
						<Engraving Date="2013-12-08"/>
					</Dates>
					<AverageDuration>0</AverageDuration>
					<BeatsPerMinute>0</BeatsPerMinute>
					<Weblink>http://www.musicistaapp.de/download/scores/Beethoven-Sonate1.musicista</Weblink>
					<Notes>Beethoven's Piano Sonata No. 1 in F minor, Op. 2, No. 1, was written in 1795 and dedicated to Joseph Haydn. It is the first piano sonata written by Beethoven. The first movement, in 2/2 time, is in sonata form. The first theme is driven by a Mannheim Rocket, very similar to the opening of the fourth movement of Mozart's Symphony No. 40. The second theme, in A-flat major, is accompanied by eighth-note octaves in the bass (usually with dominant harmony). There are two codettas; the first consists of a series of energetic descending scales in A-flat major, and the second is a lyrical passage marked con espressione. In this second codetta and in the second theme Beethoven makes interesting use of mode mixture as the right hand parts borrows from the parallel minor. The development opens with the initial theme, but is mostly dedicated to the second theme and its eighth-note accompaniment. The retransition to the main theme uses its sixteenth-note triplet. The recapitulation repeats the material from the exposition without much change, except that it stays in F minor throughout. There is a short coda. A tense, agitated feel is ubiquitous throughout the movement.</Notes>
					<Software>Musicista 1.0</Software>
				</Meta>
			</Work>
		</Category>
	</Composer>
	<Composer Name="Palestrina" Born="1525" Died="1594" Image="http://upload.wikimedia.org/wikipedia/commons/1/18/Giovanni_Pierluigi_da_Palestrina.jpg">
		<Category Name="Motets">
			<Work Name="Dies sanctificatus" Filepath="http://www.musicistaapp.de/download/scores/Palestrina-DiesSanctificatus.musicista">
				<Meta>
					<Title>Dies sanctificatus</Title>
					<People>
						<Composer FirstName="G." MiddleName="P. da" LastName="Palestrina"/>
					</People>
					<Collection/>
					<Opus Number="0" SubNumber="0"/>
					<Epoch>Renaissance</Epoch>
					<Form>Other</Form>
					<Dates>
						<Engraving Date="2011-09-07" Typesetter="Jannik Arndt"/>
					</Dates>
					<AverageDuration>0</AverageDuration>
					<BeatsPerMinute>0</BeatsPerMinute>
					<Notes/>
					<Software>Musicista 1.0</Software>
				</Meta>
			</Work>
		</Category>
	</Composer>
</Collection>

=== JannikArndt/Musicista/Collection.xml
<?xml version="1.0" encoding="utf-8"?>
<Collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="CollectionItem.xsd">
  <Composer Name="Bach" Born="1685" Died="1750" Image="images/Bach.jpg">
    <Category Name="Fugen">
      <Work Name="BWV864 Wohltemperiertes Klavier - Praeludium I" Filepath="http://musicistaapp.de/?ddownload=61">
        <Meta>
          <Title>Praeludium I</Title>
          <Subtitle>Das wohltemperierte Klavier</Subtitle>
          <People>
            <Composers>
              <Composer>
                <FirstName>Johann</FirstName>
                <MiddleName>Sebastian</MiddleName>
                <LastName>Bach</LastName>
              </Composer>
            </Composers>
            <OtherPersons>
              <Person>
                <FirstName />
                <LastName>rui.c.sousa.3</LastName>
                <Role>Uploader</Role>
                <Misc>User ID = 167019</Misc>
              </Person>
            </OtherPersons>
          </People>
          <Collection />
          <Opus Number="0" SubNumber="0" />
          <Epoch>None</Epoch>
          <Form>Other</Form>
          <Dates>
            <Engraving Date="2014-02-09T00:00:00" />
          </Dates>
          <AverageDuration>0</AverageDuration>
          <BeatsPerMinute>0</BeatsPerMinute>
          <Weblink>http://musicistaapp.de/?ddownload=61</Weblink>
          <Notes>Work Number: </Notes>
          <Software>MuseScore 1.3</Software>
        </Meta>
      </Work>
      <Work Name="BWV864 Wohltemperiertes Klavier - Fuga I" Filepath="http://musicistaapp.de/?ddownload=62">
        <Meta>
          <Title>Fuga I</Title>
          <Subtitle>a 4 Voci.</Subtitle>
          <People>
            <Composers>
              <Composer>
                <FirstName>Johann</FirstName>
                <MiddleName>Sebastian</MiddleName>
                <LastName>Bach</LastName>
              </Composer>
            </Composers>
            <OtherPersons>
              <Person>
                <FirstName />
                <LastName>cja</LastName>
                <Role>Uploader</Role>
                <Misc>User ID = 13834</Misc>
              </Person>
            </OtherPersons>
          </People>
          <Collection />
          <Opus Number="0" SubNumber="0" />
          <Epoch>Baroque</Epoch>
          <Form>Other</Form>
          <Dates>
            <Engraving Date="2011-08-26T00:00:00" />
          </Dates>
          <AverageDuration>0</AverageDuration>
          <BeatsPerMinute>0</BeatsPerMinute>
          <Copyright>publicdomain</Copyright>
          <Weblink>http://musicistaapp.de/?ddownload=62</Weblink>
          <Notes>Work Number: J.S.BACH - first Fuga (BWV 846a)</Notes>
          <Software>MuseScore 1.1</Software>
        </Meta>
      </Work>
    </Category>
  </Composer>
  <Composer Name="Beethoven" Born="1770" Died="1827" Image="images/Beethoven.jpg">
    <Category Name="Sonaten">
      <Work Name="Sonate Nr. 1" Filepath="http://musicistaapp.de/?ddownload=56">
        <Meta>
          <Title>Sonate No. 1</Title>
          <People>
            <Composers>
              <Composer>
                <FirstName>Ludwig</FirstName>
                <MiddleName>van</MiddleName>
                <LastName>Beethoven</LastName>
              </Composer>
            </Composers>
            <OtherPersons>
              <Person>
                <FirstName />
                <LastName>ClassicMan</LastName>
                <Role>Uploader</Role>
                <Misc>User ID = 19710</Misc>
              </Person>
            </OtherPersons>
          </People>
          <Collection />
          <Opus Number="2" SubNumber="1" />
          <Epoch>Classical</Epoch>
          <Form>Sonata</Form>
          <Dates>
            <Engraving Date="2013-12-08T00:00:00" />
          </Dates>
          <AverageDuration>0</AverageDuration>
          <BeatsPerMinute>0</BeatsPerMinute>
          <Weblink>http://www.musicistaapp.de/?ddownload=56</Weblink>
          <Notes>
            Work Number: Beethoven's Piano Sonata No. 1 in F minor, Op. 2, No. 1, was written in 1795 and dedicated to Joseph Haydn. It is the first piano sonata written by Beethoven.

            The third movement, a minuet in F minor, is conventional in form. It contains two repeated sections, followed by a trio in F major in two repeated sections, after which the first minuet returns. The minuet is characterized by syncopations, dramatic pauses and sharp dynamic contrast. The trio is built around longer, more lyric phrases that pass between the right and left hands in imitative polyphony.

            Transcription by jammy927.
          </Notes>
          <Software>Musicista 0.7</Software>
        </Meta>
      </Work>
    </Category>
  </Composer>
  <Composer Name="Mozart" Born="1756" Died="1791" Image="images/Mozart.jpg">
  </Composer>
</Collection>
